# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(371, 540)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settings = QtGui.QWidget()
        self.settings.setEnabled(True)
        self.settings.setObjectName(_fromUtf8("settings"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.settings)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.settings)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MathJax_Vector"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btn_mul = QtGui.QPushButton(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mul.sizePolicy().hasHeightForWidth())
        self.btn_mul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_mul.setFont(font)
        self.btn_mul.setAutoFillBackground(True)
        self.btn_mul.setStyleSheet(_fromUtf8(""))
        self.btn_mul.setCheckable(True)
        self.btn_mul.setChecked(True)
        self.btn_mul.setAutoExclusive(True)
        self.btn_mul.setAutoDefault(False)
        self.btn_mul.setFlat(True)
        self.btn_mul.setObjectName(_fromUtf8("btn_mul"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.btn_mul)
        self.horizontalLayout.addWidget(self.btn_mul)
        self.btn_div = QtGui.QPushButton(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_div.sizePolicy().hasHeightForWidth())
        self.btn_div.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_div.setFont(font)
        self.btn_div.setAutoFillBackground(True)
        self.btn_div.setCheckable(True)
        self.btn_div.setAutoExclusive(True)
        self.btn_div.setAutoDefault(False)
        self.btn_div.setFlat(True)
        self.btn_div.setObjectName(_fromUtf8("btn_div"))
        self.buttonGroup.addButton(self.btn_div)
        self.horizontalLayout.addWidget(self.btn_div)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.settings)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MathJax_Vector"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_50 = QtGui.QPushButton(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_50.sizePolicy().hasHeightForWidth())
        self.btn_50.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_50.setFont(font)
        self.btn_50.setAutoFillBackground(True)
        self.btn_50.setCheckable(True)
        self.btn_50.setChecked(True)
        self.btn_50.setAutoExclusive(True)
        self.btn_50.setAutoDefault(False)
        self.btn_50.setFlat(True)
        self.btn_50.setObjectName(_fromUtf8("btn_50"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.btn_50)
        self.horizontalLayout_2.addWidget(self.btn_50)
        self.btn_30 = QtGui.QPushButton(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_30.sizePolicy().hasHeightForWidth())
        self.btn_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_30.setFont(font)
        self.btn_30.setAutoFillBackground(True)
        self.btn_30.setCheckable(True)
        self.btn_30.setAutoExclusive(True)
        self.btn_30.setAutoDefault(False)
        self.btn_30.setFlat(True)
        self.btn_30.setObjectName(_fromUtf8("btn_30"))
        self.buttonGroup_2.addButton(self.btn_30)
        self.horizontalLayout_2.addWidget(self.btn_30)
        self.btn_10 = QtGui.QPushButton(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_10.sizePolicy().hasHeightForWidth())
        self.btn_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_10.setFont(font)
        self.btn_10.setAutoFillBackground(True)
        self.btn_10.setCheckable(True)
        self.btn_10.setAutoExclusive(True)
        self.btn_10.setAutoDefault(False)
        self.btn_10.setFlat(True)
        self.btn_10.setObjectName(_fromUtf8("btn_10"))
        self.buttonGroup_2.addButton(self.btn_10)
        self.horizontalLayout_2.addWidget(self.btn_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_3 = QtGui.QLabel(self.settings)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MathJax_Vector"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btn_do50 = QtGui.QPushButton(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_do50.sizePolicy().hasHeightForWidth())
        self.btn_do50.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_do50.setFont(font)
        self.btn_do50.setAutoFillBackground(True)
        self.btn_do50.setCheckable(True)
        self.btn_do50.setChecked(True)
        self.btn_do50.setAutoDefault(False)
        self.btn_do50.setFlat(True)
        self.btn_do50.setObjectName(_fromUtf8("btn_do50"))
        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.btn_do50)
        self.horizontalLayout_4.addWidget(self.btn_do50)
        self.btn_do100 = QtGui.QPushButton(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_do100.sizePolicy().hasHeightForWidth())
        self.btn_do100.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_do100.setFont(font)
        self.btn_do100.setAutoFillBackground(True)
        self.btn_do100.setCheckable(True)
        self.btn_do100.setAutoExclusive(False)
        self.btn_do100.setAutoDefault(False)
        self.btn_do100.setFlat(True)
        self.btn_do100.setObjectName(_fromUtf8("btn_do100"))
        self.buttonGroup_3.addButton(self.btn_do100)
        self.horizontalLayout_4.addWidget(self.btn_do100)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.btn_start = QtGui.QPushButton(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MathJax_Vector"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_start.setFont(font)
        self.btn_start.setAutoFillBackground(True)
        self.btn_start.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.btn_start.setAutoDefault(False)
        self.btn_start.setFlat(True)
        self.btn_start.setObjectName(_fromUtf8("btn_start"))
        self.verticalLayout_2.addWidget(self.btn_start)
        self.labNumer_2 = QtGui.QLabel(self.settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labNumer_2.sizePolicy().hasHeightForWidth())
        self.labNumer_2.setSizePolicy(sizePolicy)
        self.labNumer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labNumer_2.setObjectName(_fromUtf8("labNumer_2"))
        self.verticalLayout_2.addWidget(self.labNumer_2)
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        self.calc = QtGui.QWidget()
        self.calc.setObjectName(_fromUtf8("calc"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.calc)
        self.verticalLayout_3.setMargin(5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labNumer = QtGui.QLabel(self.calc)
        self.labNumer.setAlignment(QtCore.Qt.AlignCenter)
        self.labNumer.setObjectName(_fromUtf8("labNumer"))
        self.verticalLayout_3.addWidget(self.labNumer)
        self.lineZadanie = QtGui.QLineEdit(self.calc)
        self.lineZadanie.setEnabled(True)
        self.lineZadanie.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(38)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineZadanie.setFont(font)
        self.lineZadanie.setMouseTracking(False)
        self.lineZadanie.setAcceptDrops(False)
        self.lineZadanie.setText(_fromUtf8(""))
        self.lineZadanie.setFrame(True)
        self.lineZadanie.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineZadanie.setCursorPosition(0)
        self.lineZadanie.setAlignment(QtCore.Qt.AlignCenter)
        self.lineZadanie.setReadOnly(True)
        self.lineZadanie.setObjectName(_fromUtf8("lineZadanie"))
        self.verticalLayout_3.addWidget(self.lineZadanie)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_7 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_7.setFont(font)
        self.btn_7.setAutoFillBackground(True)
        self.btn_7.setAutoDefault(False)
        self.btn_7.setFlat(True)
        self.btn_7.setObjectName(_fromUtf8("btn_7"))
        self.gridLayout.addWidget(self.btn_7, 0, 0, 1, 1)
        self.btn_6 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_6.setFont(font)
        self.btn_6.setAutoFillBackground(True)
        self.btn_6.setAutoDefault(False)
        self.btn_6.setFlat(True)
        self.btn_6.setObjectName(_fromUtf8("btn_6"))
        self.gridLayout.addWidget(self.btn_6, 1, 2, 1, 1)
        self.btn_del = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_del.sizePolicy().hasHeightForWidth())
        self.btn_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dingbats"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_del.setFont(font)
        self.btn_del.setAutoFillBackground(True)
        self.btn_del.setStyleSheet(_fromUtf8("color: rgb(180, 0, 0);"))
        self.btn_del.setAutoDefault(False)
        self.btn_del.setFlat(True)
        self.btn_del.setObjectName(_fromUtf8("btn_del"))
        self.gridLayout.addWidget(self.btn_del, 3, 1, 1, 1)
        self.btn_8 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_8.setFont(font)
        self.btn_8.setAutoFillBackground(True)
        self.btn_8.setStyleSheet(_fromUtf8(""))
        self.btn_8.setAutoDefault(False)
        self.btn_8.setFlat(True)
        self.btn_8.setObjectName(_fromUtf8("btn_8"))
        self.gridLayout.addWidget(self.btn_8, 0, 1, 1, 1)
        self.btn_9 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_9.setFont(font)
        self.btn_9.setAutoFillBackground(True)
        self.btn_9.setAutoDefault(False)
        self.btn_9.setFlat(True)
        self.btn_9.setObjectName(_fromUtf8("btn_9"))
        self.gridLayout.addWidget(self.btn_9, 0, 2, 1, 1)
        self.btn_4 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_4.setFont(font)
        self.btn_4.setAutoFillBackground(True)
        self.btn_4.setAutoDefault(False)
        self.btn_4.setFlat(True)
        self.btn_4.setObjectName(_fromUtf8("btn_4"))
        self.gridLayout.addWidget(self.btn_4, 1, 0, 1, 1)
        self.btn_3 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_3.setFont(font)
        self.btn_3.setAutoFillBackground(True)
        self.btn_3.setAutoDefault(False)
        self.btn_3.setFlat(True)
        self.btn_3.setObjectName(_fromUtf8("btn_3"))
        self.gridLayout.addWidget(self.btn_3, 2, 2, 1, 1)
        self.btn_1 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_1.setFont(font)
        self.btn_1.setAutoFillBackground(True)
        self.btn_1.setAutoDefault(False)
        self.btn_1.setFlat(True)
        self.btn_1.setObjectName(_fromUtf8("btn_1"))
        self.gridLayout.addWidget(self.btn_1, 2, 0, 1, 1)
        self.btn_2 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_2.setFont(font)
        self.btn_2.setAutoFillBackground(True)
        self.btn_2.setAutoDefault(False)
        self.btn_2.setFlat(True)
        self.btn_2.setObjectName(_fromUtf8("btn_2"))
        self.gridLayout.addWidget(self.btn_2, 2, 1, 1, 1)
        self.btn_5 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_5.setFont(font)
        self.btn_5.setAutoFillBackground(True)
        self.btn_5.setAutoDefault(False)
        self.btn_5.setFlat(True)
        self.btn_5.setObjectName(_fromUtf8("btn_5"))
        self.gridLayout.addWidget(self.btn_5, 1, 1, 1, 1)
        self.btn_0 = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_0.setFont(font)
        self.btn_0.setAutoFillBackground(True)
        self.btn_0.setAutoDefault(False)
        self.btn_0.setFlat(True)
        self.btn_0.setObjectName(_fromUtf8("btn_0"))
        self.gridLayout.addWidget(self.btn_0, 3, 0, 1, 1)
        self.btn_wynik = QtGui.QPushButton(self.calc)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_wynik.sizePolicy().hasHeightForWidth())
        self.btn_wynik.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Dingbats"))
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.btn_wynik.setFont(font)
        self.btn_wynik.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn_wynik.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btn_wynik.setAcceptDrops(False)
        self.btn_wynik.setAutoFillBackground(True)
        self.btn_wynik.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.btn_wynik.setLocale(QtCore.QLocale(QtCore.QLocale.Polish, QtCore.QLocale.Poland))
        self.btn_wynik.setAutoDefault(False)
        self.btn_wynik.setFlat(True)
        self.btn_wynik.setObjectName(_fromUtf8("btn_wynik"))
        self.gridLayout.addWidget(self.btn_wynik, 3, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.calc, _fromUtf8(""))
        self.score = QtGui.QWidget()
        self.score.setObjectName(_fromUtf8("score"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.score)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.score)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MathJax_Vector"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.labWynik = QtGui.QLabel(self.score)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(22)
        self.labWynik.setFont(font)
        self.labWynik.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.labWynik.setAlignment(QtCore.Qt.AlignCenter)
        self.labWynik.setObjectName(_fromUtf8("labWynik"))
        self.verticalLayout_4.addWidget(self.labWynik)
        self.line = QtGui.QFrame(self.score)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_4.addWidget(self.line)
        self.labWynik_zly = QtGui.QLabel(self.score)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.labWynik_zly.setFont(font)
        self.labWynik_zly.setStyleSheet(_fromUtf8("color: rgb(225, 0, 0);"))
        self.labWynik_zly.setAlignment(QtCore.Qt.AlignCenter)
        self.labWynik_zly.setObjectName(_fromUtf8("labWynik_zly"))
        self.verticalLayout_4.addWidget(self.labWynik_zly)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listZle = QtGui.QListWidget(self.score)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeMono"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.listZle.setFont(font)
        self.listZle.setAutoFillBackground(False)
        self.listZle.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.listZle.setFrameShape(QtGui.QFrame.Panel)
        self.listZle.setFrameShadow(QtGui.QFrame.Sunken)
        self.listZle.setLineWidth(1)
        self.listZle.setMidLineWidth(0)
        self.listZle.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listZle.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listZle.setAlternatingRowColors(True)
        self.listZle.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.listZle.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listZle.setTextElideMode(QtCore.Qt.ElideNone)
        self.listZle.setProperty("isWrapping", False)
        self.listZle.setLayoutMode(QtGui.QListView.SinglePass)
        self.listZle.setUniformItemSizes(False)
        self.listZle.setSelectionRectVisible(False)
        self.listZle.setObjectName(_fromUtf8("listZle"))
        item = QtGui.QListWidgetItem()
        self.listZle.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listZle.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listZle.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listZle.addItem(item)
        self.horizontalLayout_3.addWidget(self.listZle)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.btn_restart = QtGui.QPushButton(self.score)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_restart.sizePolicy().hasHeightForWidth())
        self.btn_restart.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MathJax_Vector"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btn_restart.setFont(font)
        self.btn_restart.setAutoFillBackground(False)
        self.btn_restart.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);"))
        self.btn_restart.setAutoDefault(False)
        self.btn_restart.setFlat(True)
        self.btn_restart.setObjectName(_fromUtf8("btn_restart"))
        self.verticalLayout_4.addWidget(self.btn_restart)
        self.tabWidget.addTab(self.score, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Tabliczka mnożenia", None))
        self.label.setText(_translate("MainWindow", "Rodzaj działania", None))
        self.btn_mul.setText(_translate("MainWindow", "Mnożenie", None))
        self.btn_div.setText(_translate("MainWindow", "Dzielenie", None))
        self.label_2.setText(_translate("MainWindow", "Liczba zadań", None))
        self.btn_50.setText(_translate("MainWindow", "50", None))
        self.btn_30.setText(_translate("MainWindow", "30", None))
        self.btn_10.setText(_translate("MainWindow", "10", None))
        self.label_3.setText(_translate("MainWindow", "Zakres tabliczki", None))
        self.btn_do50.setText(_translate("MainWindow", "do 50", None))
        self.btn_do100.setText(_translate("MainWindow", "do 100", None))
        self.btn_start.setText(_translate("MainWindow", "START", None))
        self.labNumer_2.setText(_translate("MainWindow", "Autor: Piotr Ślęzak. Wszystkie prawa zastrzeżone", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "Settings", None))
        self.labNumer.setText(_translate("MainWindow", "Zadanie 1 z 10", None))
        self.btn_7.setText(_translate("MainWindow", "7", None))
        self.btn_6.setText(_translate("MainWindow", "6", None))
        self.btn_del.setText(_translate("MainWindow", "8", None))
        self.btn_8.setText(_translate("MainWindow", "8", None))
        self.btn_9.setText(_translate("MainWindow", "9", None))
        self.btn_4.setText(_translate("MainWindow", "4", None))
        self.btn_3.setText(_translate("MainWindow", "3", None))
        self.btn_1.setText(_translate("MainWindow", "1", None))
        self.btn_2.setText(_translate("MainWindow", "2", None))
        self.btn_5.setText(_translate("MainWindow", "5", None))
        self.btn_0.setText(_translate("MainWindow", "0", None))
        self.btn_wynik.setText(_translate("MainWindow", "4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calc), _translate("MainWindow", "Calc", None))
        self.label_4.setText(_translate("MainWindow", "WYNIK", None))
        self.labWynik.setText(_translate("MainWindow", "Poprawnie: 13 na 83", None))
        self.labWynik_zly.setText(_translate("MainWindow", "Błędy: 23", None))
        __sortingEnabled = self.listZle.isSortingEnabled()
        self.listZle.setSortingEnabled(False)
        item = self.listZle.item(0)
        item.setText(_translate("MainWindow", "2x4=13", None))
        item = self.listZle.item(1)
        item.setText(_translate("MainWindow", "12x34=452", None))
        item = self.listZle.item(2)
        item.setText(_translate("MainWindow", "34x34=1313", None))
        item = self.listZle.item(3)
        item.setText(_translate("MainWindow", "34x33=1351", None))
        self.listZle.setSortingEnabled(__sortingEnabled)
        self.btn_restart.setText(_translate("MainWindow", "RESTART", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.score), _translate("MainWindow", "Score", None))

